version: '2'
services:
  batch:
    image: lucaspugliese/agibank-batch:1.0.0
    container_name: agibank-batch
    volumes:
      - $HOME/data/input:/root/data/input
      - $HOME/data/done:/root/data/done
      - $HOME/data/output:/root/data/output
      - $HOME/data/invalid:/root/data/invalid